remote_theme: "jekyll/minima@1e8a445"

minima:
  skin: dark
  
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/benjacksondev"

author: benjacksondev


