remote_theme: "jekyll/minima@1e8a445"

minima:
  skin: solarized-dark
  
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/benjacksondev"
    - title: Linkedin
      icon: linkedin
      url: "https://www.linkedin.com/in/benjacksondev"

author: benjacksondev

description: Reasoning my way through dark rooms. 

nav_pages:
  - 

hide_site_feed_link: true
